services:
  - type: worker
    name: goryachev-studio-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: TELEGRAM_TOKEN
        value: 7755776750:AAHaFINi5nwT__E93inT9GfxkQycGUf-HS0
