services:
  - type: web
    name: goryachev-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        value: ${BOT_TOKEN}
      - key: ADMIN_ID
        value: ${ADMIN_ID}
