services:
  - type: web
    name: goryachev-studio-bot
    env: python
    region: frankfurt
    plan: free
    branch: main
    buildCommand: ""
    startCommand: "python bot.py"
    envVars:
      - key: TOKEN
        value: 7755776750:AAHaFINi5nwT__E93inT9GfxkQycGUf-HS0
      - key: ADMIN_CHAT_ID
        value: 7681110461
